version: "3.7"
 
services:
  internal-chat:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      PORT: 3000
    volumes:
      - ./src:/app/src
    ports:
      - "3000:3000"
      - "8181:8181"
    command: yarn dev